# Generated by Django 2.0.13 on 2020-01-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='media/placeholder.png', upload_to='img'),
        ),
    ]
