# Generated by Django 2.0.13 on 2020-01-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200131_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='home/YKsenia/my-first-blog/media/img/'),
        ),
    ]
