# Generated by Django 2.0.13 on 2020-04-17 21:59

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_huckyou_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='huckyou',
            name='article',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.HuckYou'),
        ),
    ]
