# Generated by Django 2.0.13 on 2020-04-17 22:39

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200417_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='huckyou',
            name='file',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
