# Generated by Django 2.0.13 on 2020-04-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_huckyou_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='huckyou',
            name='label',
            field=models.CharField(default='practice', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='murich',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
