# Generated by Django 2.0.13 on 2020-06-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200501_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='slug',
            field=models.SlugField(default='post_images/how-to-learn-programming-AMS.jpg'),
            preserve_default=False,
        ),
    ]
