# Generated by Django 2.0.13 on 2020-08-16 13:51

import blog.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_images_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='slug',
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[500, 300], upload_to=blog.models.get_image_filename),
        ),
    ]
