# Generated by Django 2.0.13 on 2022-01-24 20:25

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_huckyou_hitcount_hit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='article',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
